### ISSUE TITLE
Cannot install in Angular 9

### ISSUE THREAD

**Issue by timrhaynes** [arthurvaverko/ngx-highlight#16]
Following the instructions on how to install and include the module, compiling gets this error:

ERROR in ./node_modules/ngx-highlight/highlight.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: <myrepo>\node_modules\ngx-highlight\highlight.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a 
sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Dev\MOE\source\repos\OpenSIMS-UI\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:933:23)
    at <myrepo>\node_modules\@ngtools\webpack\src\loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by 3idiotGit** [comment]
Any update about this issue please?
