### ISSUE TITLE
Error Building 

### ISSUE THREAD

**Issue by gregduffield** [arthurvaverko/ngx-highlight#6]
Have followed the instructions, but with the addition of ngx-highlight the Angular CLI can no longer build the project, see the error below.

```
ERROR in ./node_modules/ngx-highlight/highlight.module.ts
Module build failed: Error: C:\Repos\proteo-analytics\node_modules\ngx-highlight\highlight.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or
 i
Module build failed: Error: C:\Repos\proteo-analytics\node_modules\ngx-highlight\highlight.module.ts is missing from the TypeScript compilation. Please make sure ite library repository to alert its author is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Repos\proteo-analytics\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:653:23)
    at plugin.done.then (C:\Repos\proteo-analytics\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/shared/shared.module.ts 30:25-66
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by arthurvaverko-kaltura** [comment]
You use webpack or system js ?

**Comment by gregduffield** [comment]
I am using Webpack via the angular cli (1.6.3). This is a standard project created via the CLI.

Please let me know if you need anything else.

Thanks
greg

**Comment by arthurvaverko-kaltura** [comment]
Well it was a while since i updated this project.. Ill try to get to it to
reproduce ..

Atthe mean time if you see something that can help add more comments ..

**Comment by olsn** [comment]
Same for me - the issue is that this repo ships the TS-files with NPM, but this should actually never be done - since there are a many drawbacks to this, some being:
- compiling takes longer in any case
- compiling might not even be possible because certain configuration might be missing
- import-path issues due to the location of the files now being inside the node_modules
- and more

Basically this would be like shipping the C++ source-code instead of a .dll-library. So instead of shipping the TS-files, you should add a compile-step to compile to JavaScript and Typing-Files and ship those instead. And since this is a public repo you could even have github do all the work for free, simply setup a travis.yml-file to do that (have a look here for an example - https://github.com/bcoe/travis-deploy-example)

As a temporary solution, since it's only one directive: I've copy/pasted the directive-file to my sources and added it directly as a declaration to my app-module - works like a charm, thank you for the directive! :+1:

**Comment by arthurvaverko-kaltura** [comment]
happy to help... thanks for the example and detailed explanation.
unfortunately I don't have much time to do all that .. (i will get to it
one day)
at the meantime if any one feels that he can package this better please
pull request me :)..

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by moarief** [comment]
> As a temporary solution, since it's only one directive: I've copy/pasted the directive-file to my sources and added it directly as a declaration to my app-module - works like a charm, thank you for the directive! 

Could someone show me how? Or which fills? I have tried this, but the highlighter only highlights on single character and word??

**Comment by moarief** [comment]
Found the error :)
